id: P9D1B7DF2
initial_creation_type: input
source_metadata:
  title: Ngöndro Commentary by Chökyi Drakpa
  language: en
  description: 'The commentary on the preliminary practices of Longchen Nyingtik by
    Chökyi Drakpa (chos kyi grags pa):'
  volume:
    a1bb42f69113407d963921f9f13beae6:
      title: 'A Torch for the Path to Omniscience: A Word by Word Commentary to the
        Longchen Nyingtik Ngöndro'
      parent: null
created_at: '2022-02-28T22:48:13.458168'
last_modified_at: '2022-02-28T22:48:13.458175'
